---
- name: Download WordPress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
  become: yes

- name: Update default Apache site
  become: yes
  lineinfile:
    dest=/etc/apache2/sites-enabled/000-default.conf
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache

- name: Copy sample config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php
  become: yes

- name: Update WordPress config file
  replace:
    dest=/var/www/wordpress/wp-config.php
    regexp="{{ item.regexp }}"
    replace="{{ item.replace }}"
  with_items:
    - { regexp: 'database_name_here', replace: 'wordpress' }
    - { regexp: 'username_here', replace: 'wordpress' }
    - { regexp: 'password_here', replace: 'Ab@12345'}
  become: yes
