---
# tasks file for server

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install required software
  apt:
    name: ['apache2', 'mysql-server', 'mysql-client', 'php', 'php-mysql', 'libapache2-mod-php','php-cli', 'php-cgi',
  'php-gd', 'python-mysqldb'] 

          #name={{ item }} 
    state: present
  become: yes
  #with_items:
  #- apache2
  #  - mysql-server
  #  - mysql-client
  # - php7.0
  # - php7.0-mysql
  #  - libapache2-mod-php7.0
  #- php7.0-cli
      #- php7.0-cgi
      #- php7.0-gd
      #- python-mysqldb
